name: News Fetch

on:
  workflow_dispatch:       # Manual trigger
  schedule:                # Optional: fetch news automatically
    - cron: '0 * * * *'    # Every hour

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: varsha12
          MYSQL_DATABASE: dailyscope
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do
            if mysqladmin ping -h mysql -uroot -p"$MYSQL_ROOT_PASSWORD" --silent; then
              echo "MySQL is ready!"
              break
            fi
            sleep 2
          done

      - name: Run PHP script
        env:
          DB_HOST: mysql
          DB_USER: root
          DB_PASSWORD: varsha12
          DB_NAME: dailyscope
        run: php ./news_fetch.php

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: news-fetch-log
          path: news_fetch.log



